version: '3.8'

services:
  misaka-bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "-f", "python bot.py", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s